version: '3.7'
services:
  spring-camel-api:
    image: grantlee289/spring-camel-api
    container_name: spring-camel-api-app
    expose:
      - "8084/tcp"
      - "8085/tcp"
    volumes:
      - /opt/apps/spring-camel-api/logs:/logs
      - /opt/apps/spring-camel-file-mover/from:/to
    restart: unless-stopped